spring.application.name=cucumber
spring.datasource.url= ${POSTGRESDB_DB_URL}
spring.datasource.username= ${POSTGRESDB_USER}
spring.datasource.password= ${POSTGRESDB_ROOT_PASSWORD}
spring.datasource.driver-class-name= org.postgresql.Driver

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql= true
spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect